# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Typesense - open source, typo tolerant search engine for everyone.
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
   Typesense is an open source, typo tolerant search engine that delivers fast and relevant results out-of-the-box.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://typesense.org" # the base hostname & protocol for your site, e.g. http://example.com
versions:
  - 0.12.0
  - 0.11.2
  - 0.11.1
  - 0.11.0
  - 0.10.1
  - 0.10.0
  - 0.9.2
  - 0.9.1
  - 0.9.0

premium_versions:
  - 10.3.0
  - 10.2.0

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks

plugins:
  - jekyll-feed

nav_pages:
  - index.html.md
  - guide.html
  - api.html
  - downloads.html.md
  - contact.html.md

defaults:
  - scope:
      path: "docs/0.9.0"
    values:
      permalink: "/docs/0.9.0/:basename/"
  - scope:
      path: "docs/0.9.1"
    values:
      permalink: "/docs/0.9.1/:basename/"
  - scope:
      path: "docs/0.9.2"
    values:
      permalink: "/docs/0.9.2/:basename/"
  - scope:
      path: "docs/0.10.0"
    values:
      permalink: "/docs/0.10.0/:basename/"
  - scope:
      path: "docs/0.10.1"
    values:
      permalink: "/docs/0.10.1/:basename/"
  - scope:
      path: "docs/0.11.0"
    values:
      permalink: "/docs/0.11.0/:basename/"
  - scope:
      path: "docs/0.11.1"
    values:
        permalink: "/docs/0.11.1/:basename/"
  - scope:
      path: "docs/0.11.2"
    values:
      permalink: "/docs/0.11.2/:basename/"
  - scope:
      path: "docs/0.12.0"
    values:
      permalink: "/docs/0.12.0/:basename/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
